added support for both static and dynamic path
cloud-bulldozer/scale-ci-deploy pull request #132
Opened 2021-02-09 07:21 UTC by amitsagtani97

- When installed from install scripts, it will create a dynamic path.
- When using individual scripts, it will pick the static path if the dynamic path doesn't exist.

2021-02-09 11:40 UTC, rsevilla87 commented on OCP-4.X/roles/openshift-install/tasks/main.yml
> +
```suggestion

- name: Get scale_ci_deploy directory
  set_fact:
    scale_ci_deploy_diretory: "{{ lookup('env', 'dynamic_deploy_path') | default('{{ ansible_user_dir }}/scale-ci-deploy', true) }}"
```

2021-02-09 11:40 UTC, rsevilla87 commented on OCP-4.X/roles/openshift-install/tasks/main.yml
> +    - "{{ dynamic_deploy_path }}/bin"
```suggestion
    - "{{ scale_ci_deploy_diretory }}/bin"
```

2021-02-09 11:40 UTC, rsevilla87 commented on OCP-4.X/roles/openshift-install/tasks/main.yml
> +    dest: "{{ dynamic_deploy_path }}/bin/{{ openshift_client_location | basename }}"
```suggestion
    dest: "{{ scale_ci_deploy_diretory }}/bin/{{ openshift_client_location | basename }}"
```

2021-02-09 11:41 UTC, rsevilla87 commented on OCP-4.X/roles/openshift-install/tasks/main.yml
> +    cd {{ dynamic_deploy_path }}/bin
```suggestion
    cd {{ scale_ci_deploy_diretory }}/bin
```

2021-02-09 11:41 UTC, rsevilla87 commented on OCP-4.X/roles/openshift-install/tasks/main.yml
> +      cd {{ dynamic_deploy_path }}/bin
```suggestion
      cd {{ scale_ci_deploy_diretory }}/bin
```

2021-02-09 11:41 UTC, rsevilla87 commented on OCP-4.X/roles/openshift-install/tasks/main.yml
> +      dest: "{{ dynamic_deploy_path }}/bin/openshift-install"
```suggestion
      dest: "{{ scale_ci_deploy_diretory }}/bin/openshift-install"
```

2021-02-09 11:41 UTC, rsevilla87 commented on OCP-4.X/roles/openshift-install/tasks/main.yml
> +      dest: "{{ dynamic_deploy_path }}/bin/openshift-install"
And so on :)

2021-02-09 11:41 UTC, rsevilla87 requested changes
Have added some comments

2021-02-10 08:49 UTC, rsevilla87 approved these changes
LGTM!

2021-03-01 13:49 UTC, chaitanyaenr commented on OCP-4.X/clean-on-osp.yml
> +    scale_ci_deploy_diretory: "{{ lookup('env', 'dynamic_deploy_path') | default('scale-ci-deploy', true) }}"
s/diretory/directory

2021-03-01 13:49 UTC, chaitanyaenr commented on OCP-4.X/clean-on-osp.yml
> +        cd {{ ansible_user_dir }}/{{ scale_ci_deploy_diretory }}/
Won't this have conflicts when we try to install multiple clusters on the same jump host?

2021-03-08 07:33 UTC, amitsagtani97 commented on OCP-4.X/clean-on-osp.yml
> +        cd {{ ansible_user_dir }}/{{ scale_ci_deploy_diretory }}/
this scale_ci_deploy_diretory contains the dynamic install address from here - https://github.com/cloud-bulldozer/scale-ci-deploy/blob/fix_dynamic_path/OCP-4.X/roles/openshift-install/tasks/main.yml#L14

2021-03-08 13:42 UTC, chaitanyaenr approved these changes
LGTM

2021-03-08 13:42 UTC, merged