CI for scale-ci-deploy
cloud-bulldozer/scale-ci-deploy pull request #138
Opened 2021-03-10 12:01 UTC by Harshith-umesh

2021-03-15 07:56 UTC, amitsagtani97 reviewed
@Harshith-umesh can we create a test pipeline on jenkins and run this pr. Running it on jenkins will give us an clear view, if we are missing something or not.

2021-03-19 11:31 UTC, amitsagtani97 commented
/rerun aws

2021-03-19 11:41 UTC, amitsagtani97 commented
/rerun aws

2021-03-19 13:03 UTC, chaitanyaenr reviewed
Minor nits

2021-03-19 13:03 UTC, chaitanyaenr commented on CI/README.md
> +Where platform can be either `aws`, `azure` or `gcp`.
We might want to add in OSP as well.

2021-03-19 14:08 UTC, chaitanyaenr commented on CI/run_ci.sh
> +ansible-playbook -v -i inventory OCP-4.X/deploy-cluster.yml -e platform=${_platform}
We might want to run the cluster cleanup after reporting the results irrespective of where it's a pass/fail.

2021-03-19 14:17 UTC, Harshith-umesh commented on CI/run_ci.sh
> +ansible-playbook -v -i inventory OCP-4.X/deploy-cluster.yml -e platform=${_platform}
yes , was thinking about this as well ! 
so will:
cd /root/scale-ci-<clustername>-aws/
./bin/openshift-installer destroy cluster 
work?

2021-03-22 10:33 UTC, rsevilla87 commented on CI/properties_files/aws_openshift_installer.sh
> +export ORCHESTRATION_USER= #required field
Given that some variables are common to all platforms, I think we should move them to a common_properties.sh file and source it from each platform properties file.

2021-03-22 10:47 UTC, Harshith-umesh commented on CI/properties_files/aws_openshift_installer.sh
> +export ORCHESTRATION_USER= #required field
@rsevilla87 the variables common to all platforms , which have same value in all 3 clouds are very few and @chaitanyaenr suggested that we add a "/rerun all" step, so i think it might be better if each platform_openshift_installer.sh files have their separate variables , it won't lead to confusion if all variables required for a particular platform are in one place . thoughts?

2021-03-23 17:31 UTC, Harshith-umesh commented
/rerun azure

2021-03-23 17:38 UTC, Harshith-umesh commented
/rerun azure

2021-03-23 18:38 UTC, Harshith-umesh commented
/rerun gcp

2021-03-24 07:14 UTC, Harshith-umesh commented
/rerun all

2021-03-24 09:04 UTC, Harshith-umesh commented
/rerun azure

2021-03-24 10:04 UTC, Harshith-umesh commented
/rerun all

2021-03-24 10:13 UTC, rsevilla87 commented on CI/properties_files/aws_openshift_installer.sh
> +export ORCHESTRATION_USER= #required field
There're a bunch of "duplicated" parameters. credentials, post-install, cluster-version, elasticsearch, I'm just suggesting to
move those common parameters to a new `common.sh` file, and then `source common.sh` from each <platform>_opesnhift_installer.sh file. This will improve readability and help in future maintenance.

2021-03-24 12:12 UTC, Harshith-umesh commented
/rerun gcp

2021-03-24 13:03 UTC, Harshith-umesh commented
/rerun gcp

2021-03-24 13:11 UTC, Harshith-umesh commented
/rerun azure

2021-03-24 13:20 UTC, Harshith-umesh commented
/rerun aws

2021-03-24 17:14 UTC, Harshith-umesh commented
/rerun gcp

2021-03-24 18:15 UTC, Harshith-umesh commented
/rerun gcp

2021-03-24 18:38 UTC, Harshith-umesh commented
/rerun all

2021-03-25 04:32 UTC, Harshith-umesh commented
/rerun aws

2021-03-25 04:51 UTC, Harshith-umesh commented
/rerun azure

2021-03-25 05:04 UTC, Harshith-umesh commented
/rerun gcp

2021-03-31 05:57 UTC, Harshith-umesh commented
/rerun azure

2021-03-31 07:11 UTC, Harshith-umesh commented
/rerun aws

2021-03-31 07:16 UTC, Harshith-umesh commented
/rerun aws

2021-03-31 08:06 UTC, Harshith-umesh commented
/rerun azure

2021-03-31 09:25 UTC, Harshith-umesh commented
/rerun azure

2021-04-05 10:17 UTC, Harshith-umesh commented
/rerun all

2021-04-05 17:41 UTC, Harshith-umesh commented
/rerun azure

2021-04-06 05:42 UTC, Harshith-umesh commented
/rerun gcp

2021-04-06 08:14 UTC, amitsagtani97 requested changes

2021-04-06 08:14 UTC, amitsagtani97 commented on CI/properties_files/aws_openshift_installer.sh
> +export ORCHESTRATION_USER= #required field
@Harshith-umesh check these common vars -> https://github.com/cloud-bulldozer/scale-ci-deploy/blob/master/OCP-4.X/vars/install-common-vars.yml 
as @rsevilla87 suggested, we can have a separate common vars file and initialize them at the beginning and then we can initialize the platform specific vars.

2021-04-06 14:19 UTC, Harshith-umesh commented
/rerun all

2021-04-06 19:03 UTC, Harshith-umesh commented
/rerun aws

2021-04-07 06:41 UTC, Harshith-umesh commented
/rerun all

2021-04-07 07:18 UTC, Harshith-umesh commented
/rerun all

2021-04-07 07:25 UTC, Harshith-umesh commented
/rerun all

2021-04-07 11:59 UTC, Harshith-umesh commented
@amitsagtani97 have made the requested changes , created a common_vars.sh file in /properties_files folder

2021-04-07 15:00 UTC, chaitanyaenr commented on OCP-4.X/roles/cerberus/tasks/main.yml
>      url: "{{ cerberus_url }}"
We might want to rebase the PR with the master @Harshith-umesh.

2021-04-07 15:07 UTC, Harshith-umesh commented on OCP-4.X/roles/cerberus/tasks/main.yml
>      url: "{{ cerberus_url }}"
done @chaitanyaenr

2021-04-07 15:08 UTC, chaitanyaenr approved these changes
LGTM, nice work @Harshith-umesh!

2021-04-12 13:02 UTC, mohit-sheth approved these changes
LGTM

2021-04-12 15:05 UTC, amitsagtani97 requested changes

2021-04-12 15:05 UTC, amitsagtani97 commented on CI/common.sh
> +#! /bin/bash
#!/bin/bash   remove extra space

2021-04-12 16:31 UTC, amitsagtani97 approved these changes
LGTM! nice work @Harshith-umesh

2021-04-13 08:56 UTC, rsevilla87 commented on CI/properties_files/aws_openshift_installer.sh
>  export OPENSHIFT_MASTER_ROOT_VOLUME_SIZE=220
export OPENSHIFT_MASTER_ROOT_VOLUME_SIZE=50

2021-04-13 08:56 UTC, rsevilla87 commented on CI/properties_files/aws_openshift_installer.sh
>  export OPENSHIFT_INFRA_NODE_VOLUME_SIZE=100
export OPENSHIFT_INFRA_NODE_VOLUME_SIZE=10

2021-04-13 09:02 UTC, rsevilla87 commented on CI/properties_files/aws_openshift_installer.sh
> +export OPENSHIFT_PROMETHEUS_STORAGE_SIZE=500Gi
export OPENSHIFT_PROMETHEUS_STORAGE_SIZE=10Gi

2021-04-13 09:02 UTC, rsevilla87 commented on CI/properties_files/aws_openshift_installer.sh
> +export OPENSHIFT_ALERTMANAGER_STORAGE_SIZE=20Gi
export OPENSHIFT_ALERTMANAGER_STORAGE_SIZE=1Gi

2021-04-13 09:03 UTC, rsevilla87 commented on CI/properties_files/gcp_openshift_installer.sh
> +export OPENSHIFT_PROMETHEUS_STORAGE_SIZE=500Gi
export OPENSHIFT_PROMETHEUS_STORAGE_SIZE=5Gi

2021-04-13 09:03 UTC, rsevilla87 commented on CI/properties_files/gcp_openshift_installer.sh
> +export OPENSHIFT_ALERTMANAGER_STORAGE_SIZE=20Gi
```suggestion
export OPENSHIFT_ALERTMANAGER_STORAGE_SIZE=1Gi
```

2021-04-13 09:03 UTC, rsevilla87 commented on CI/properties_files/openstack_openshift_installer.sh
> +export OPENSHIFT_PROMETHEUS_STORAGE_SIZE=10Gi
```suggestion
export OPENSHIFT_PROMETHEUS_STORAGE_SIZE=5Gi
```

2021-04-13 09:08 UTC, rsevilla87 commented on CI/properties_files/aws_openshift_installer.sh
> +export OPENSHIFT_WORKLOAD_NODE_VOLUME_SIZE=500
```suggestion
export OPENSHIFT_WORKLOAD_NODE_VOLUME_SIZE=120
```

2021-04-13 09:10 UTC, rsevilla87 commented on CI/properties_files/azure_openshift_installer.sh
> +export OPENSHIFT_WORKER_ROOT_VOLUME_SIZE=1024
```suggestion
export OPENSHIFT_WORKER_ROOT_VOLUME_SIZE=128
```

2021-04-13 09:12 UTC, rsevilla87 commented on CI/properties_files/azure_openshift_installer.sh
> +export OPENSHIFT_PROMETHEUS_STORAGE_SIZE=10Gi
```suggestion
export OPENSHIFT_PROMETHEUS_STORAGE_SIZE=5Gi
```

2021-04-13 09:12 UTC, rsevilla87 commented on CI/properties_files/azure_openshift_installer.sh
> +export OPENSHIFT_ALERTMANAGER_STORAGE_SIZE=2Gi
```suggestion
export OPENSHIFT_ALERTMANAGER_STORAGE_SIZE=1Gi
```

2021-04-13 09:13 UTC, rsevilla87 commented on CI/properties_files/gcp_openshift_installer.sh
> +export OPENSHIFT_INFRA_NODE_INSTANCE_TYPE=n1-standard-64
```suggestion
export OPENSHIFT_INFRA_NODE_INSTANCE_TYPE=n1-standard-4
```

2021-04-13 09:13 UTC, rsevilla87 commented on CI/properties_files/gcp_openshift_installer.sh
> +export OPENSHIFT_MASTER_INSTANCE_TYPE=n1-standard-16
```suggestion
export OPENSHIFT_MASTER_INSTANCE_TYPE=n1-standard-8
```

2021-04-13 09:13 UTC, rsevilla87 commented on CI/properties_files/gcp_openshift_installer.sh
> +export OPENSHIFT_WORKLOAD_NODE_VOLUME_SIZE=500
```suggestion
export OPENSHIFT_WORKLOAD_NODE_VOLUME_SIZE=120
```

2021-04-13 09:14 UTC, rsevilla87 commented on CI/properties_files/gcp_openshift_installer.sh
> +export OPENSHIFT_MASTER_ROOT_VOLUME_SIZE=220
```suggestion
export OPENSHIFT_MASTER_ROOT_VOLUME_SIZE=120
```

2021-04-13 12:37 UTC, rsevilla87 commented
/rerun azure

2021-04-14 09:29 UTC, rsevilla87 commented
/rerun aws

2021-04-14 10:27 UTC, rsevilla87 approved these changes
LGTM!

2021-04-14 10:28 UTC, merged